from __future__ import annotations

from .schemas import AdMaterialTemplate


TEMPLATES: list[AdMaterialTemplate] = [
    AdMaterialTemplate(
        id="byte-camera-renewal",
        name="相机翻新",
        category="视频编辑",
        description="参考原视频中的相机外观、比例、颜色和材质，生成机身全新的同款相机视频。",
        industry_tags=["3C", "相机", "模板复刻"],
        theme_categories=["电商带货", "产品展示", "视频编辑"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/17_2.mp4",
        slots=[
            {
                "key": "reference_video",
                "type": "video",
                "required": True,
                "label": "参考视频",
                "default_url": "asset://asset-20260224185116-9zhtg",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-makeup-cut-join",
        name="妆容快切衔接",
        category="时序补全",
        description="参考第一段人物视频生成化妆步骤快切，并自然衔接第二段视频。",
        industry_tags=["美妆", "人物", "时序补全"],
        theme_categories=["生活方式", "美妆个护", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-06-01__result01__QIGKb0.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151837-4dqnp",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-06-01__ref01__video1__NUuybh.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260408151837-jcjgb",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-06-01__ref02__video2__APttbS.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-gift-cream-replace",
        name="礼盒商品替换",
        category="视频编辑",
        description="将参考视频礼盒中的香水替换为参考图片中的面霜，并保持原运镜不变。",
        industry_tags=["美妆", "礼盒", "商品替换"],
        theme_categories=["电商带货", "产品展示", "美妆个护"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/39_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185114-9ld2t",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/39_2.jpeg",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185114-gkn4w",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/39_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-dogfood-package-replace",
        name="狗粮包装替换",
        category="时序补全",
        description="自动跟踪参考视频中的所有狗粮包装袋，并替换为参考图片中的新包装样式。",
        industry_tags=["宠物", "包装替换", "时序补全"],
        theme_categories=["电商带货", "产品替换", "宠物用品"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-06-04__result01__KY0QbX.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-rnww2",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/16_2.png",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185116-ltclw",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/16_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-perfume-light-sweep",
        name="香水扫光",
        category="视频编辑",
        description="保持参考视频中的香水主体与氛围不变，将产品级光线调整为从左到右扫光并加入丁达尔效应。",
        industry_tags=["美妆", "香水", "光效编辑"],
        theme_categories=["商业广告", "产品展示", "美妆个护"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-02-03__result01__OHVEbO.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151818-pw4ks",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-02-03__ref01__video1__Hch5bw.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260408151818-sjckn",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-apple-tea-fpv-ad",
        name="苹果果茶广告",
        category="参考生成",
        description="参考第一视角视频构图、首尾帧图片和背景音乐，生成苹果果茶限定款宣传广告。",
        industry_tags=["饮品", "果茶", "参考生成"],
        theme_categories=["商业广告", "食品饮品", "第一视角"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/32_6.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185115-857xj",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/32_3.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185115-m98j4",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/32_4.png",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-nxqsl",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/32_1.mp4",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185115-vgw76",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-glasses-model-replace",
        name="眼镜模特替换",
        category="视频编辑",
        description="将参考视频中的眼镜带货模特替换为参考图片中的欧美人，并将语言改为英语，保留动作和运镜。",
        industry_tags=["眼镜", "人物替换", "视频编辑"],
        theme_categories=["电商带货", "人物替换", "跨境带货"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/40_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185115-j7xjt",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/40_2.png",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-rcs4v",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/40_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-anime-fireworks-color-fix",
        name="花火大会色彩修复",
        category="视频编辑",
        description="修复参考动漫花火大会视频的色彩表现，保留原片内容、节奏和运镜。",
        industry_tags=["动漫", "色彩修复", "视频编辑"],
        theme_categories=["3D动漫", "动漫分镜", "视频修复"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/12_2.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185116-whcxg",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/12_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-pixel-fight-reference",
        name="像素打斗场面",
        category="参考生成",
        description="参考视频的人物动作和镜头语言，用三张参考图生成像素游戏风格打斗场面，并引用参考音乐。",
        industry_tags=["游戏", "像素风", "参考生成"],
        theme_categories=["3D动漫", "游戏像素", "动作打斗"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        cover_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/30_2.png",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185115-jkxvm",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/30_2.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185115-5776n",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/30_3.png",
            },
            {
                "key": "reference_image_3",
                "type": "image",
                "required": True,
                "label": "图片3",
                "default_url": "asset://asset-20260224185115-zd5pg",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/30_4.png",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-6qwld",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/30_1.mp4",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185115-bs8l6",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-lion-bullet-time-extend",
        name="狮子子弹时间续写",
        category="时序补全",
        description="续写参考草原追逐视频，生成狮子冲刺起跳、子弹时间环绕和远景收束的动作段落。",
        industry_tags=["动物", "动作续写", "时序补全"],
        theme_categories=["自然纪实", "生态动物", "运镜特效", "动作打斗"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/22_2.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-8v2sq",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/22_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-woodcut-horse-motion",
        name="马上有福木刻动效",
        category="参考生成",
        description="参考藏书票图片的黑白木刻版画风格和参考视频的拉镜头运镜，生成骏马复活动效。",
        industry_tags=["传统艺术", "版画", "参考生成"],
        theme_categories=["国风艺术", "传统文化", "动效生成"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/31_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185114-ww95m",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/31_1.png",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185114-5zp94",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/31_2.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-runway-clothes-replace",
        name="走秀服装替换",
        category="视频编辑",
        description="将参考走秀视频中模特穿着的衣服替换为参考图片中的衣服，并保持人物动作和运镜。",
        industry_tags=["服装", "走秀", "视频编辑"],
        theme_categories=["电商带货", "服饰穿搭", "人物替换"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/44_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185115-g2cjw",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/44_2.jpeg",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-b9mnv",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/44_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-revenge-chess-anime",
        name="复仇棋局动漫分镜",
        category="参考生成",
        description="参考多张分镜图、背景图和御姐音色，生成复仇主题智性博弈式战斗动漫片段。",
        industry_tags=["动漫", "分镜", "参考生成"],
        theme_categories=["3D动漫", "动漫分镜", "情绪叙事"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_10.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185115-jtzz8",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_1.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185115-dpcnt",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_2.png",
            },
            {
                "key": "reference_image_3",
                "type": "image",
                "required": True,
                "label": "图片3",
                "default_url": "asset://asset-20260224185115-f894x",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_4.png",
            },
            {
                "key": "reference_image_4",
                "type": "image",
                "required": True,
                "label": "图片4",
                "default_url": "asset://asset-20260224185115-n6ntn",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_5.png",
            },
            {
                "key": "reference_image_5",
                "type": "image",
                "required": True,
                "label": "图片5",
                "default_url": "asset://asset-20260224185115-t4rd2",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_6.png",
            },
            {
                "key": "reference_image_6",
                "type": "image",
                "required": True,
                "label": "图片6",
                "default_url": "asset://asset-20260224185115-lcfd4",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_7.png",
            },
            {
                "key": "reference_image_7",
                "type": "image",
                "required": True,
                "label": "图片7",
                "default_url": "asset://asset-20260224185115-vvdhh",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/36_8.png",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185115-scvln",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-caterpillar-cocoon-prequel",
        name="毛毛虫蝶蛹前置补全",
        category="时序补全",
        description="结合参考视频补全前置镜头，生成毛毛虫变成蝶蛹并保持画面风格一致。",
        industry_tags=["自然", "前置补全", "时序补全"],
        theme_categories=["自然纪实", "时序补全", "生态动物"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/18_2.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-2wwbd",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/18_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-window-spring-extension",
        name="窗景春日延长",
        category="时序补全",
        description="向后延长参考视频，将窗外景色丝滑变为春天暖色调，并呈现女生面部惊讶特写。",
        industry_tags=["春天", "延长", "时序补全"],
        theme_categories=["微电影", "情绪叙事", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-04-03__result01__D6yIbJ.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151837-jqgxn",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-04-03__ref01__video1__EJz0by.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-kdrama-restaurant-noodle",
        name="韩剧餐馆吃面甜感短片",
        category="参考生成",
        description="参考男女主图片和吃面动作视频，生成温馨韩剧生活氛围感餐馆短片。",
        industry_tags=["韩剧", "生活氛围", "参考生成"],
        theme_categories=["微电影", "生活方式", "情绪叙事"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/1_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-lxmhw",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/1_1.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185116-j68n4",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/1_3.png",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185116-5nd7q",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/1_2.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-fpv-apple-pie-baking",
        name="第一视角苹果派烘焙",
        category="参考生成",
        description="参考第一视角构图、菜谱书页和苹果派图片，生成沉浸式厨房烘焙 vlog。",
        industry_tags=["烘焙", "第一视角", "参考生成"],
        theme_categories=["商业广告", "食品饮品", "生活方式", "第一视角"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/5_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-chsbs",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/5_1.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185116-gcrtw",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/5_2.png",
            },
            {
                "key": "reference_image_3",
                "type": "image",
                "required": True,
                "label": "图片3",
                "default_url": "asset://asset-20260224185116-g4px5",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/5_3.png",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-war-elephant-battlefield",
        name="战象女将沙漠战场",
        category="参考生成",
        description="参考女战士、装甲战象、士兵服装和战场风格图，生成史诗级电影感古代沙漠战场视频。",
        industry_tags=["战场", "史诗电影感", "参考生成"],
        theme_categories=["微电影", "史诗大片", "战争动作"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/6_5.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-xbqvs",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/6_1.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185116-2zwkz",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/6_2.png",
            },
            {
                "key": "reference_image_3",
                "type": "image",
                "required": True,
                "label": "图片3",
                "default_url": "asset://asset-20260224185116-vdhjg",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/6_3.png",
            },
            {
                "key": "reference_image_4",
                "type": "image",
                "required": True,
                "label": "图片4",
                "default_url": "asset://asset-20260224185116-2nbbj",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/6_4.png",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-flower-arrangement-timeline",
        name="女孩插花过程补全",
        category="时序补全",
        description="从两个参考视频之间补全女孩插花的过程，生成自然连贯的时序补全视频。",
        industry_tags=["插花", "过程补全", "时序补全"],
        theme_categories=["生活方式", "时序补全", "人物动作"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/27_3.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-99lcv",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/27_1.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260224185117-qvn6q",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/27_2.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-boy-hug-grandpa-colorize",
        name="男孩拥抱老人上色短片",
        category="参考生成",
        description="参考男孩、老人图片和拥抱动作视频，生成3D动画电影风格的温暖重逢短片。",
        industry_tags=["3D动画", "情感叙事", "参考生成"],
        theme_categories=["3D动漫", "情绪叙事", "家庭亲情"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/3_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-fl8q5",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/3_2.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185116-rjhp6",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/3_3.png",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185116-44pxt",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/3_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-horse-red-envelope-prequel",
        name="马年红包前置延长",
        category="时序补全",
        description="向前延长参考视频，生成暖金红国风马年红包产品展示并衔接参考视频。",
        industry_tags=["红包", "产品展示", "时序补全"],
        theme_categories=["电商带货", "产品展示", "国风艺术"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_3_3.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-2z85l",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_3_1.mp4",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185117-8gtr9",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-cloud-ice-cream-cabin",
        name="云朵冰淇淋机舱幻想",
        category="参考合成",
        description="以机舱首帧、冰淇淋和角色图片为参考，生成云朵变冰淇淋并配合参考音频的幻想短片。",
        industry_tags=["幻想", "冰淇淋", "参考合成"],
        theme_categories=["3D动漫", "奇幻创意", "食品饮品"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/38_6.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185114-qmg8h",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/38_1.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185114-gclt8",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/38_2.png",
            },
            {
                "key": "reference_image_3",
                "type": "image",
                "required": True,
                "label": "图片3",
                "default_url": "asset://asset-20260224185114-xvvwv",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/38_3.png",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185114-565c8",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-wuxia-sword-duel-extension",
        name="武侠双剑交锋延长",
        category="时序补全",
        description="向后延长参考视频，生成白衣黑衣二人剑影交错、双剑相撞的武侠交锋片段。",
        industry_tags=["武侠", "动作延长", "时序补全"],
        theme_categories=["微电影", "国风武侠", "动作打斗"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-04-02__result01__AVESbx.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151837-zhtzj",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-04-02__ref01__video1__JBhPbo.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-fpv-drone-flight-edit",
        name="FPV 穿越机运镜转换",
        category="视频编辑",
        description="将参考视频的普通无人机高空滑行运镜转换为带侧倾、俯冲和翻转的 FPV 竞技视角。",
        industry_tags=["无人机", "FPV", "视频编辑"],
        theme_categories=["商业广告", "运镜特效", "航拍运动"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-03-02__result01__IhllbG.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151818-z58cv",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-03-02__ref01__video1__HKk7b5.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-female-anchor-opening",
        name="女主播开场词",
        category="视频编辑",
        description="让参考女主播在指定场景中说开场词，台词声音参考音频素材。",
        industry_tags=["主播", "口播", "视频编辑"],
        theme_categories=["电商带货", "口播带货", "人物口播"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/15_4.mp4",
        slots=[
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185116-s5nfl",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/15_2.png",
            },
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-jw64c",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/15_1.png",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185116-l8q68",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-new-year-one-take-extension",
        name="新年一镜到底延长",
        category="时序补全",
        description="延长参考视频，用一镜到底运镜穿过厨房、客厅与室外烟花场景，生成新年喜庆氛围短片。",
        industry_tags=["新年", "一镜到底", "时序补全"],
        theme_categories=["生活方式", "国风艺术", "时序补全", "运镜特效"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/48_4.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-kdtp2",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/48_1.mp4",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185115-p2cdz",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-gallery-painting-transition",
        name="美术馆画内转场",
        category="时序补全",
        description="衔接三段参考视频，从拱形窗进入美术馆室内，再让镜头进入画内完成沉浸式转场。",
        industry_tags=["美术馆", "画内转场", "时序补全"],
        theme_categories=["国风艺术", "微电影", "时序补全", "运镜特效"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/23_4.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-krtsr",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/23_1.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260224185117-rbfz9",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/23_2.mp4",
            },
            {
                "key": "reference_video_3",
                "type": "video",
                "required": True,
                "label": "视频3",
                "default_url": "asset://asset-20260224185117-4z4wc",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/23_3.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-clay-pancake-style-edit",
        name="粘土动画煎饼风格化",
        category="视频编辑",
        description="将参考视频中的摊煎饼画面彻底转换为色彩明快、带手工捏制纹理的 3D 粘土动画风格。",
        industry_tags=["煎饼", "粘土动画", "视频编辑"],
        theme_categories=["3D动漫", "生活方式", "食品饮品", "视频修复"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-01-04__result01__XpIhbd.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151817-q5fnw",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-01-04__ref01__video1__Ay2Fbl.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-camera-crew-removal-audio-replace",
        name="摄像穿帮去除与换声",
        category="视频编辑",
        description="去除参考视频中镜子内和人物旁的摄像穿帮部分，并替换为参考音频。",
        industry_tags=["穿帮修复", "换声", "视频编辑"],
        theme_categories=["视频修复", "生活方式", "运镜特效"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/45_4.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-x9qsd",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/45_1.mp4",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185115-zsdrw",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-story-prequel-extension",
        name="前半故事情节补全",
        category="时序补全",
        description="根据参考视频生成前半部分故事情节，补全更完整的叙事开端。",
        industry_tags=["故事补全", "前置补全", "时序补全"],
        theme_categories=["微电影", "情绪叙事", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/19_2.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-x4qh7",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/19_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-reference-music-mv",
        name="参考画风音乐 MV",
        category="参考生成",
        description="参考图片的画面画风，为指定音频生成音乐 MV。",
        industry_tags=["音乐MV", "画风参考", "参考生成"],
        theme_categories=["商业广告", "3D动漫", "情绪叙事"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/14_3.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-67fq6",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/14_1.png",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185116-4kqfg",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-passerby-removal-edit",
        name="镜头路人删除",
        category="视频编辑",
        description="删除镜头前走过的路人，保持原视频运镜和画面节奏不变。",
        industry_tags=["路人移除", "视频修复", "视频编辑"],
        theme_categories=["商业广告", "生活方式", "运镜特效"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/43_3.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-55dm2",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/43_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-hutong-rooftop-parkour-prequel",
        name="胡同屋面跑酷前置补全",
        category="时序补全",
        description="向前延长参考视频，生成胡同灰瓦屋面一镜到底跑酷，并自然接入原视频。",
        industry_tags=["跑酷", "前置补全", "一镜到底"],
        theme_categories=["微电影", "动作打斗", "运镜特效", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-05-03__result01__CjLWbO.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151837-bqf26",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-timeline-05-03__ref01__video1__YeyJb4.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-apocalyptic-overgrown-city-edit",
        name="末世废墟绿植化",
        category="视频编辑",
        description="保持原视频运镜、街道路网和空间结构不变，仅将外观状态改为长满绿植的末世废墟。",
        industry_tags=["末世废墟", "场景风格化", "视频编辑"],
        theme_categories=["商业广告", "微电影", "自然纪实", "运镜特效"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-02-01__result01__PRDdbZ.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260408151817-rg4k4",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151817-9cvxf",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-02-01__ref01__video1__Aqxjbm.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-guofeng-lantern-papercut-horse-transition",
        name="国风灯笼剪纸马渐变",
        category="时序补全",
        description="将灯笼光影、剪纸马和壁画画面以国风慢节奏渐变融合，形成丝滑连续转场。",
        industry_tags=["国风", "剪纸马", "渐变转场"],
        theme_categories=["国风艺术", "商业广告", "运镜特效", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_2_4.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-7mdq6",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_2_1.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260224185117-9frtz",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_2_2.mp4",
            },
            {
                "key": "reference_video_3",
                "type": "video",
                "required": True,
                "label": "视频3",
                "default_url": "asset://asset-20260224185117-gwv25",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_2_3.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-japanese-dialogue-story-extension",
        name="日语台词故事续写",
        category="时序补全",
        description="续写参考视频后续剧情，人物台词使用日语并添加对应字幕。",
        industry_tags=["故事续写", "日语台词", "字幕"],
        theme_categories=["微电影", "3D动漫", "情绪叙事", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/24_2.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-vm7nm",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/24_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-child-dinosaur-drawing-process",
        name="儿童画恐龙过程补全",
        category="时序补全",
        description="以第一段视频为开头、第二段视频为结尾，生成小孩子画恐龙的完整过程。",
        industry_tags=["儿童绘画", "过程补全", "时序补全"],
        theme_categories=["生活方式", "3D动漫", "情绪叙事", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/25_3.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-26jbl",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/25_1.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260224185117-75gmc",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/25_2.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-outdoor-hiking-shoe-ad",
        name="户外徒步登山鞋广告",
        category="参考生成",
        description="参考群山、人物和登山鞋图片，生成电影感户外徒步广告片。",
        industry_tags=["户外徒步", "登山鞋", "商业广告"],
        theme_categories=["商业广告", "产品展示", "生活方式", "自然纪实"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/4_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185116-zvjlj",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/4_1.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185116-b4gw8",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/4_2.png",
            },
            {
                "key": "reference_image_3",
                "type": "image",
                "required": True,
                "label": "图片3",
                "default_url": "asset://asset-20260224185116-lff7w",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/4_3.png",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-captain-robot-handdrawn-replace",
        name="船长机械人手绘替换",
        category="视频编辑",
        description="保持原视频说话节奏和情绪，将船长替换为参考机械人并转为温暖手绘动画质感。",
        industry_tags=["人物替换", "机械人", "手绘动画"],
        theme_categories=["人物替换", "3D动漫", "微电影", "商业广告"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-01-02__result01__KRr3b3.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260408151818-7gw6k",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-01-02__ref02__image1__AhxtbY.jpg",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260408151818-lqqdf",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/media/tpl-doc-20260408150656-edit-01-02__ref01__video1__R4FQbb.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-dark-cyber-sci-fi-prequel",
        name="暗黑赛博科幻前置补全",
        category="时序补全",
        description="向前延长参考视频，生成暗黑赛博科幻废土、生化体与机械触须冲突的前置片段。",
        industry_tags=["科幻", "赛博朋克", "前置补全"],
        theme_categories=["3D动漫", "动作打斗", "微电影", "运镜特效", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/53_3.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-f9nfx",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/53_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-house-blue-snow-edit",
        name="雪天蓝墙房屋改色",
        category="视频编辑",
        description="将参考视频中的房子外立面墙壁刷成蓝色，并参考图片中的雪天天气和光线。",
        industry_tags=["房屋", "外立面改色", "雪天氛围"],
        theme_categories=["视频编辑", "建筑空间", "风格迁移"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/46_4.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185115-dg62w",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/46_2.jpeg",
            },
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185115-6x477",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/edit/46_1.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-orange-cat-new-year-timeline",
        name="小橘猫新年三幕衔接",
        category="时序补全",
        description="衔接森林、古镇与暖居三段参考视频，以小橘猫跑动为主线生成冷暖递进的新年电影感短片。",
        industry_tags=["小橘猫", "新年", "三段衔接"],
        theme_categories=["生活方式", "国风艺术", "情绪叙事", "时序补全"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_1_4.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185117-c2r4r",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_1_1.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260224185117-l27sd",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_1_2.mp4",
            },
            {
                "key": "reference_video_3",
                "type": "video",
                "required": True,
                "label": "视频3",
                "default_url": "asset://asset-20260224185117-cvbp2",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/timeline/cn_1_3.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-ceo-rain-romance-reference",
        name="奶油霸总雨夜短剧",
        category="参考生成",
        description="参考霸总、女主、服装、雨夜背景、文字图和音频，生成清新奶油画风短剧快切。",
        industry_tags=["短剧", "霸总", "雨夜告白"],
        theme_categories=["微电影", "情绪叙事", "商业广告", "参考生成"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/37_8.mp4",
        slots=[
            {
                "key": "reference_image_1",
                "type": "image",
                "required": True,
                "label": "图片1",
                "default_url": "asset://asset-20260224185115-hnjhb",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/37_1.png",
            },
            {
                "key": "reference_image_2",
                "type": "image",
                "required": True,
                "label": "图片2",
                "default_url": "asset://asset-20260224185115-8gghm",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/37_2.png",
            },
            {
                "key": "reference_image_3",
                "type": "image",
                "required": True,
                "label": "图片3",
                "default_url": "asset://asset-20260224185115-cjkwr",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/37_3.png",
            },
            {
                "key": "reference_image_4",
                "type": "image",
                "required": True,
                "label": "图片4",
                "default_url": "asset://asset-20260224185115-pxbk9",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/37_5.png",
            },
            {
                "key": "reference_image_5",
                "type": "image",
                "required": True,
                "label": "图片5",
                "default_url": "asset://asset-20260224185115-2c698",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/37_6.png",
            },
            {
                "key": "reference_audio_1",
                "type": "audio",
                "required": True,
                "label": "音频1",
                "default_url": "asset://asset-20260224185115-dp9qm",
            },
        ],
    ),
    AdMaterialTemplate(
        id="byte-ancient-architecture-skywell-reference",
        name="古建天井旋转仰拍",
        category="参考生成",
        description="参考旋转运镜和鸟群视频，生成中国古建筑内部仰拍天井与八角木质穹顶。",
        industry_tags=["古建筑", "天井", "旋转运镜"],
        theme_categories=["国风艺术", "微电影", "运镜特效", "参考生成"],
        supported_ratios=["16:9"],
        default_ratio="16:9",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        preview_video_url="https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/34_4.mp4",
        slots=[
            {
                "key": "reference_video_1",
                "type": "video",
                "required": True,
                "label": "视频1",
                "default_url": "asset://asset-20260224185114-hj8nr",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/34_1.mp4",
            },
            {
                "key": "reference_video_2",
                "type": "video",
                "required": True,
                "label": "视频2",
                "default_url": "asset://asset-20260224185114-99dxs",
                "preview_url": "https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/presets/experience/gen_video/templates/reference/reference/34_2.mp4",
            },
        ],
    ),
    AdMaterialTemplate(
        id="hero-product-clean",
        name="商品主图质感展示",
        category="商品主图",
        description="适合白底商品图、详情页主图视频和电商首屏展示。",
        industry_tags=["美妆", "3C", "家居", "食品"],
        supported_ratios=["9:16", "1:1", "3:4", "16:9"],
        default_ratio="9:16",
        default_duration=8,
        default_resolution="720p",
        default_generate_audio=False,
        slots=[
            {"key": "product_image", "type": "image", "required": True, "label": "商品图片"},
            {"key": "product_name", "type": "text", "required": True, "label": "商品名称"},
            {"key": "selling_points", "type": "text", "required": True, "label": "核心卖点"},
        ],
    ),
    AdMaterialTemplate(
        id="viral-ad-cuts",
        name="爆款投流快切",
        category="爆款投流",
        description="快节奏展示商品卖点，适合抖音、视频号投流素材。",
        industry_tags=["美妆", "服饰", "食品", "数码"],
        supported_ratios=["9:16", "3:4"],
        default_ratio="9:16",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        slots=[
            {"key": "product_image", "type": "image", "required": True, "label": "商品图片"},
            {"key": "selling_points", "type": "text", "required": True, "label": "投流卖点"},
            {"key": "reference_audio", "type": "audio", "required": False, "label": "节奏参考音频"},
        ],
    ),
    AdMaterialTemplate(
        id="virtual-host-demo",
        name="虚拟达人讲解",
        category="达人口播",
        description="虚拟人像手持或展示商品，输出带台词的口播素材。",
        industry_tags=["美妆", "保健", "家居", "母婴"],
        supported_ratios=["9:16", "16:9"],
        default_ratio="9:16",
        default_duration=11,
        default_resolution="720p",
        default_generate_audio=True,
        slots=[
            {"key": "avatar", "type": "avatar", "required": False, "label": "虚拟人像 asset"},
            {"key": "product_image", "type": "image", "required": True, "label": "商品图片"},
            {"key": "selling_points", "type": "text", "required": True, "label": "口播卖点"},
        ],
    ),
    AdMaterialTemplate(
        id="product-replace-edit",
        name="爆款视频商品替换",
        category="视频编辑",
        description="上传参考视频和新商品图，保持原动作和运镜，替换视频中的商品。",
        industry_tags=["通用"],
        supported_ratios=["adaptive", "9:16", "16:9", "1:1"],
        default_ratio="adaptive",
        default_duration=8,
        default_resolution="720p",
        default_generate_audio=True,
        slots=[
            {"key": "reference_video", "type": "video", "required": True, "label": "参考视频"},
            {"key": "product_image", "type": "image", "required": True, "label": "新商品图片"},
        ],
    ),
]


def list_templates() -> list[AdMaterialTemplate]:
    return TEMPLATES


def get_template(template_id: str) -> AdMaterialTemplate | None:
    tid = (template_id or "").strip()
    return next((tpl for tpl in TEMPLATES if tpl.id == tid), None)
